server:
  port: 13000
spring:
  datasource:
    username: root
    password: 913147306
    url: jdbc:mysql://localhost:3306/trip_destination
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: destination
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
