#logging:
#  level:
#    reactor:
#      netty: INFO
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
server:
  port: 8080
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true


      routes:
          - id: destination
            uri: lb://destination
            predicates:
              - Path=/destination/**
            filters:
              - StripPrefix=1
          - id: user
            uri: lb://user
            predicates:
              - Path=/user/**
            filters:
              - StripPrefix=1
          - id: article
            uri: lb://article
            predicates:
              - Path=/article/**
            filters:
              - StripPrefix=1


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

